
// DO NOT EDIT. This file is generated by Studio.
export interface UserProfile {
  /**
   * Unique identifier for the user profile, matching Firebase Auth UID.
   */
  id: string;
  /**
   * User's full name.
   */
  name: string;
  /**
   * User's phone number.
   */
  phoneNumber: string;
  /**
   * User's email address.
   */
  email: string;
  /**
   * User's city of residence.
   */
  city: string;
  /**
   * URL to the user's uploaded Driving License ID (optional).
   */
  drivingLicenseId?: string;
  /**
   * Indicates if the user's profile is verified by an admin.
   */
  profileVerified: boolean;
  /**
   * User's emergency contact information.
   */
  emergencyContact?: string;
}
export interface PickupRequest {
  /**
   * Unique identifier for the pickup request.
   */
  id: string;
  /**
   * UID of the user creating the request.
   */
  userProfileId: string;
  /**
   * Starting location of the ride.
   */
  startingLocation: string;
  /**
   * Destination of the ride.
   */
  destination: string;
  /**
   * ISO string of the ride's date and time.
   */
  dateTime: string;
  /**
   * Type of vehicle (Bike / Scooty).
   */
  vehicleType: "Bike" | "Scooty";
  /**
   * Number of seats available (default 1).
   */
  seatsAvailable: number;
  /**
   * Expected cost of the ride (optional).
   */
  expectedCost?: number;
  /**
   * Rider's preferred route.
   */
  routePreference?: string;
  /**
   * The current status of the request (e.g., 'open', 'matched', 'cancelled').
   */
  status: "open" | "matched" | "cancelled";
  /**
   * Timestamp of when the request was created.
   */
  createdAt: any;
  /**
   * List of user IDs who have rejected this request.
   */
  rejectedBy?: string[];
  /**
   * The UID of the passenger who has been matched with this ride offer.
   */
  matchedPassengerId?: string;
}
export interface ServiceRequest {
  /**
   * Unique identifier for the service request.
   */
  id: string;
  /**
   * UID of the user creating the request.
   */
  userProfileId: string;
  /**
   * Pickup location for the service.
   */
  pickupLocation: string;
  /**
   * Destination for the service.
   */
  destination: string;
  /**
   * ISO string of the service's date and time.
   */
  dateTime: string;
  /**
   * Maximum amount the passenger is willing to pay.
   */
  maxAmountWillingToPay: number;
  /**
   * Passenger's preferred route.
   */
  preferredRoute?: string;
  /**
   * The current status of the request (e.g., 'open', 'matched', 'cancelled').
   */
  status: "open" | "matched" | "cancelled";
  /**
   * Timestamp of when the request was created.
   */
  createdAt: any;
  /**
   * Reference to the associated ride document.
   */
  rideId?: string;
  /**
   * List of user IDs who have rejected this request.
   */
  rejectedBy?: string[];
  /**
   * The UID of the driver who has been matched with this service request.
   */
  matchedDriverId?: string;
}
export interface Ride {
  /**
   * Unique identifier for the ride.
   */
  id: string;
  /**
   * UID of the user who is driving.
   */
  driverId: string;
  /**
   * UID of the user who is the passenger.
   */
  passengerId: string;
  /**
   * Reference to the PickupRequest, if the ride originated from one.
   */
  pickupRequestId?: string;
  /**
   * Reference to the ServiceRequest, if the ride originated from one.
   */
  serviceRequestId?: string;
  /**
   * Array containing the UIDs of both the rider and the passenger.
   */
  participantIds: string[];
  /**
   * Status of the ride.
   */
  status: "requested" | "confirmed" | "start_pending" | "in-progress" | "completion_pending" | "completed" | "cancelled" | "cancelled_by_passenger" | "cancelled_by_provider";
  /**
   * The agreed shared cost between the rider and passenger.
   */
  sharedCost: number;
  /**
   * ISO string of the confirmed ride's date and time.
   */
  dateTime: string;
  /**
   * Timestamp of when the ride was created.
   */
  createdAt: any;
  /**
   * Timestamp of when the ride request was accepted by the driver.
   */
  acceptedAt?: any;
  /**
   * The starting location of the ride.
   */
  fromLocation: string;
  /**
   * The destination of the ride.
   */
  toLocation: string;
  /**
   * 4-digit OTP for ride verification.
   */
  rideOtp?: string;
  /**
   * Indicates if the OTP has been verified by the rider.
   */
  otpVerified?: boolean;
  /**
   * Indicates if the rider has confirmed the ride start.
   */
  riderStartConfirmed?: boolean;
  /**
   * Indicates if the passenger has confirmed the ride start.
   */
  passengerStartConfirmed?: boolean;
  /**
   * Indicates if the rider has confirmed the ride completion.
   */
  riderCompletionConfirmed?: boolean;
  /**
   * Indicates if the passenger has confirmed the ride completion.
   */
  passengerCompletionConfirmed?: boolean;
  /**
   * Timestamp of when the ride was completed.
   */
  completedAt?: any;
}
export interface Chat {
  /**
   * Unique identifier for the chat.
   */
  id: string;
  /**
   * Array containing the UIDs of all participants.
   */
  participantIds: string[];
  /**
   * Array of message objects in the chat.
   */
  messages?: any[];
  /**
   * Timestamp of the last message sent.
   */
  lastMessageAt: any;
}
export interface ChatMessage {
  /**
   * UID of the user who sent the message.
   */
  senderId: string;
  /**
   * The content of the message.
   */
  text: string;
  /**
   * Timestamp when the message was sent.
   */
  createdAt: any;
}
export interface SosAlert {
  /**
   * Unique identifier for the SOS alert.
   */
  id: string;
  /**
   * UID of the user who triggered the alert.
   */
  userProfileId: string;
  /**
   * Reference to the Ride during which the alert was triggered.
   */
  rideId: string;
  /**
   * Timestamp when the alert was triggered.
   */
  timestamp: any;
  /**
   * Location of the user when the alert was triggered (e.g., coordinates).
   */
  location: string;
}
export interface Notification {
  /**
   * Unique identifier for the notification.
   */
  id: string;
  /**
   * UID of the user who will receive the notification.
   */
  userId: string;
  /**
   * ID of the related ride, if applicable.
   */
  rideId?: string;
  /**
   * The content of the notification message.
   */
  message: string;
  /**
   * The type of notification.
   */
  type: "ride_cancelled" | "ride_accepted" | "ride_requested" | "new_message" | "ride_completed";
  /**
   * Indicates who cancelled the ride.
   */
  cancelledBy?: "passenger" | "provider";
  /**
   * True if the user has read the notification.
   */
  isRead: boolean;
  /**
   * Timestamp of when the notification was created.
   */
  createdAt: any;
}
