
// DO NOT EDIT. This file is generated by Studio.
export interface UserProfile {
  /**
   * Unique identifier for the user profile, matching Firebase Auth UID.
   */
  id: string;
  /**
   * User's full name.
   */
  name: string;
  /**
   * User's phone number.
   */
  phoneNumber: string;
  /**
   * User's email address.
   */
  email: string;
  /**
   * User's city of residence.
   */
  city: string;
  /**
   * URL to the user's uploaded Driving License ID (optional).
   */
  drivingLicenseId?: string;
  /**
   * Indicates if the user's profile is verified by an admin.
   */
  profileVerified: boolean;
  /**
   * User's emergency contact information.
   */
  emergencyContact?: string;
}
export interface Ride {
  /**
   * Unique identifier for the ride.
   */
  id: string;
  /**
   * UID of the user who is driving. Null if it's a passenger's open request.
   */
  driverId: string | null;
  /**
   * UID of the user who is the passenger. Null if it's a driver's open offer.
   */
  passengerId: string | null;
  /**
   * Array containing the UIDs of the rider and/or the passenger.
   */
  participantIds: string[];
  /**
   * Status of the ride.
   */
  status: "offering" | "pending" | "confirmed" | "in-progress" | "completed" | "cancelled";
  /**
   * The agreed shared cost between the rider and passenger.
   */
  sharedCost: number;
  /**
   * ISO string of the confirmed ride's date and time.
   */
  dateTime: string;
  /**
   * Timestamp of when the ride was created.
   */
  createdAt: any;
  /**
   * Timestamp of when the ride request was accepted by the driver.
   */
  acceptedAt?: any;
  /**
   * The starting location of the ride.
   */
  fromLocation: string;
  /**
   * The destination of the ride.
   */
  toLocation: string;
  /**
   * Type of vehicle (Bike / Scooty).
   */
  vehicleType?: "Bike" | "Scooty";
  /**
   * 4-digit OTP for ride verification.
   */
  rideOtp?: string;
  /**
   * Indicates if the OTP has been verified by the rider.
   */
  otpVerified?: boolean;
  /**
   * Indicates if the rider has confirmed the ride start.
   */
  riderStarted?: boolean;
  /**
   * Indicates if the passenger has confirmed the ride start.
   */
  passengerStarted?: boolean;
  /**
   * Indicates if the rider has confirmed the ride completion.
   */
  riderCompleted?: boolean;
  /**
   * Indicates if the passenger has confirmed the ride completion.
   */
  passengerCompleted?: boolean;
  /**
   * Timestamp of when the ride was completed.
   */
  completedAt?: any;
  /**
   * UID of the user who cancelled the ride.
   */
  cancelledBy?: string;
  /**
   * Timestamp of when the ride was cancelled.
   */
  cancelledAt?: any;
}
export interface ChatMessage {
  /**
   * UID of the user who sent the message.
   */
  senderId: string;
  /**
   * The content of the message.
   */
  text: string;
  /**
   * Timestamp when the message was sent.
   */
  createdAt: any;
}
export interface SosAlert {
  /**
   * Unique identifier for the SOS alert.
   */
  id: string;
  /**
   * UID of the user who triggered the alert.
   */
  userProfileId: string;
  /**
   * Reference to the Ride during which the alert was triggered.
   */
  rideId: string;
  /**
   * Timestamp when the alert was triggered.
   */
  timestamp: any;
  /**
   * Location of the user when the alert was triggered (e.g., coordinates).
   */
  location: string;
}
export interface Notification {
  /**
   * Unique identifier for the notification.
   */
  id: string;
  /**
   * UID of the user who will receive the notification.
   */
  userId: string;
  /**
   * ID of the related ride, if applicable.
   */
  rideId?: string;
  /**
   * The content of the notification message.
   */
  message: string;
  /**
   * The type of notification.
   */
  type: "ride_cancelled" | "ride_accepted" | "ride_requested" | "new_message" | "ride_completed";
  /**
   * Indicates who cancelled the ride.
   */
  cancelledBy?: "passenger" | "provider";
  /**
   * True if the user has read the notification.
   */
  isRead: boolean;
  /**
   * Timestamp of when the notification was created.
   */
  createdAt: any;
}
