// DO NOT EDIT. This file is generated by Studio.
export interface UserProfile {
  /**
   * Unique identifier for the user profile.
   */
  id: string;
  /**
   * User's full name.
   */
  name: string;
  /**
   * User's phone number, used for OTP verification.
   */
  phoneNumber: string;
  /**
   * User's email address.
   */
  email: string;
  /**
   * User's city of residence.
   */
  city: string;
  /**
   * User's Aadhaar ID or College ID (optional).
   */
  aadhaarId?: string;
  /**
   * Indicates if the user's profile is verified by an admin.
   */
  profileVerified?: boolean;
  /**
   * User's emergency contact phone number.
   */
  emergencyContact?: string;
  /**
   * Indicates if the user is a rider (pickup provider).
   */
  isRider?: boolean;
  /**
   * Indicates if the user is a passenger (service requester).
   */
  isPassenger?: boolean;
}
export interface PickupRequest {
  /**
   * Unique identifier for the pickup request.
   */
  id: string;
  /**
   * Reference to UserProfile of the rider creating the request. (Relationship: UserProfile 1:N PickupRequest)
   */
  riderId: string;
  /**
   * Starting location of the ride.
   */
  startingLocation: string;
  /**
   * Destination of the ride.
   */
  destination: string;
  /**
   * Date and time of the ride.
   */
  dateTime: string;
  /**
   * Type of vehicle (Bike / Scooty).
   */
  vehicleType: string;
  /**
   * Number of seats available (default 1).
   */
  seatsAvailable: number;
  /**
   * Expected cost of the ride (optional).
   */
  expectedCost?: number;
  /**
   * Rider's preferred route.
   */
  routePreference?: string;
}
export interface ServiceRequest {
  /**
   * Unique identifier for the service request.
   */
  id: string;
  /**
   * Reference to UserProfile of the passenger creating the request. (Relationship: UserProfile 1:N ServiceRequest)
   */
  passengerId: string;
  /**
   * Pickup location for the service.
   */
  pickupLocation: string;
  /**
   * Destination for the service.
   */
  destination: string;
  /**
   * Date and time for the service.
   */
  dateTime: string;
  /**
   * Maximum amount willing to pay.
   */
  maxAmount: number;
  /**
   * Passenger's preferred route.
   */
  preferredRoute?: string;
}
export interface Ride {
  /**
   * Unique identifier for the ride.
   */
  id: string;
  /**
   * Reference to the PickupRequest. (Relationship: PickupRequest 1:N Ride)
   */
  pickupRequestId: string;
  /**
   * Reference to the ServiceRequest. (Relationship: ServiceRequest 1:N Ride)
   */
  serviceRequestId: string;
  /**
   * Reference to the UserProfile of the rider. (Relationship: UserProfile 1:N Ride)
   */
  riderId: string;
  /**
   * Reference to the UserProfile of the passenger. (Relationship: UserProfile 1:N Ride)
   */
  passengerId: string;
  /**
   * Status of the ride (Requested, Accepted, Confirmed, Completed, Cancelled).
   */
  status: string;
  /**
   * The agreed shared cost between the rider and passenger.
   */
  sharedCost?: number;
}
export interface Chat {
  /**
   * Unique identifier for the chat.
   */
  id: string;
  /**
   * Reference to the Ride. (Relationship: Ride 1:N Chat)
   */
  rideId: string;
  /**
   * Array of message objects in the chat.
   */
  messages?: string[];
}
export interface SOSAlert {
  /**
   * Unique identifier for the SOS alert.
   */
  id: string;
  /**
   * Reference to the UserProfile who triggered the alert. (Relationship: UserProfile 1:N SOSAlert)
   */
  userId: string;
  /**
   * Reference to the Ride during which the alert was triggered. (Relationship: Ride 1:N SOSAlert)
   */
  rideId: string;
  /**
   * Timestamp when the alert was triggered.
   */
  timestamp: string;
  /**
   * Location of the user when the alert was triggered (e.g., coordinates).
   */
  location: string;
  /**
   * Additional details about the emergency situation.
   */
  details?: string;
}
